### ISSUE TITLE
Consider migrating away from Boilertalk/BigInt

### ISSUE THREAD

**Issue by fhoy** [Bouke/SRP#11]
According to https://github.com/Boilertalk/BigInt.swift/blob/master/README.md:
> _This fork will not be maintained any more in favour of the original library which is now also officially supported on Linux and the newest Swift version. Please switch to [the original library](https://github.com/attaswift/BigInt) ASAP_

This deprecation warning was added 22 June 2018. Has migrating to the "original library" been considered?

**Comment by Bouke** [comment]
This package used the "original library" previously, but [switched to that fork](https://github.com/Bouke/SRP/commit/1ce4ec7b933aae733df625838e1c307e0356b1f8) to support Swift 4.1. We should definitely switch back to the original library. Would you be interested in creating a PR?

**Comment by Bouke** [comment]
55786803815f14920c22b287e474547cb3c99902

**Comment by fhoy** [comment]
Thanks! Sorry for not responding earlier.
