### ISSUE TITLE
 Showing Recent Messages The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0

### ISSUE THREAD

**Issue by GSerjo** [Bouke/SRP#21]
Hi,

After updating to the latest package I'm getting the following error: `
The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0`. could you please specify iOS version.

https://stackoverflow.com/questions/64309926/how-to-set-minimum-supported-ios-version

thank you for the awesome package!

**Comment by Bouke** [comment]
Can you create a PR for this? I’m not into building iOS apps myself. Is there some way to add iOS to the test suite?

**Comment by Bouke** [comment]
Can you verify PR #22 and tell me if that works for you?

**Comment by GSerjo** [comment]
thank you! I was planning to do the same this evening..  and the error because of this. probably xcode should display a warning/error one of the dependencies has minimal requirements 

```
let package = Package(
    name: "swift-crypto",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
        .watchOS(.v6),
        .tvOS(.v13),
    ],
```
