### ISSUE TITLE
publicKey and privateKey not random

### ISSUE THREAD

**Issue by GreenSnakeLinux** [Bouke/SRP#23]
Hello

Can you provide a test with [srptools](https://pypi.python.org/pypi/srptools) with same privateKey in the init ?

Example:
```
var auth_private: [UInt8] = (Array)(Data("2469779c25ab55977dae0e8e4d1bc6a70b8e9cf62864991777457c316c3f6dcf".utf8))
let client = Client<SHA512>(username: username, password: password, group: .N3072, privateKey: Data(privateKey))
```

thanks

**Comment by Bouke** [comment]
I looks like you have a hex encoded key, but you aren’t decoding it as such. The constructor takes a byte array, so first decode it before passing it to the constructor.
