### ISSUE TITLE
Using between iOS app and server

### ISSUE THREAD

**Issue by rchatham** [Bouke/SRP#9]
I was curious if this solution will work to securely send passwords between the client being an iOS device and the server and what the best way to incorporate the library into an iOS app is. Any help would be appreciated.

**Comment by Bouke** [comment]
SRP does facilitate sending of passwords. It does authentication; client proofs it has possession over the password. As a result of the algorithm, a secure key is used that can be used to start an encrypted channel. SRP can be seen as a challenge-response algorithm and can be useful in situations where the client can't share the password with the server to proof possession over the key.

**Comment by rchatham** [comment]
This seems like an incredibly promising library. 

Do you have a recommended way of managing this dependency for iOS?

**Comment by Bouke** [comment]
I haven't written iOS apps in a while, so not completely sure what the state of things is. SwiftPM can be used to generate an Xcode project file. You might want to look into that, you would have to change the project file to target the iOS SDK and possibly other changes as well. Hopefully SwiftPM gets support for iOS and macOS (gui) apps in the future.

**Comment by rchatham** [comment]
Cool. I'll look into it! Thanks for the awesome library!
